<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\HappyBoxx.ServiceDefaults\HappyBoxx.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HappyBoxx.BuildingBlocks\HappyBoxx.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HappyBoxx.Catalog.UnitTests" />
  </ItemGroup>

</Project>
