import { useEffect, useState, type ReactNode } from 'react';
import { UiLanguageContext, type UiLanguage } from './UiLanguageContext';

const LANGUAGE_STORAGE_KEY = 'happyboxx.ui-language';

const translations: Record<string, string> = {
  'Account menu': 'Menu tài khoản',
  'Warehouse manager': 'Quản lý kho',
  'Warehouse Admin': 'Quản trị kho hàng',
  Dashboard: 'Bảng điều khiển',
  'Key metrics and alerts': 'Các chỉ số chính và cảnh báo',
  Inventory: 'Hàng tồn kho',
  'All Products': 'Tất cả sản phẩm',
  'Everything in the catalog': 'Tất cả sản phẩm trong danh mục',
  'Fresh Produce': 'Nông sản tươi',
  Vegetables: 'Rau củ',
  Fruits: 'Trái cây',
  Packaging: 'Bao bì',
  Containers: 'Hộp đựng',
  'Stock Levels': 'Mức tồn kho',
  'On-hand quantities and low-stock alerts': 'Số lượng hiện có và cảnh báo tồn kho thấp',
  Categories: 'Danh mục',
  'Organise the catalog': 'Sắp xếp danh mục sản phẩm',
  'Spoilage & Quality Control': 'Hư hỏng và kiểm soát chất lượng',
  'Record spoilage, inspections and write-offs': 'Ghi nhận hư hỏng, kiểm tra và loại bỏ hàng',
  Orders: 'Đơn hàng',
  Pending: 'Đang chờ',
  'New orders awaiting confirmation': 'Đơn hàng mới đang chờ xác nhận',
  'Processing / Picking': 'Đang xử lý / lấy hàng',
  'Orders being picked and packed': 'Đơn hàng đang được lấy và đóng gói',
  'Ready for Dispatch': 'Sẵn sàng giao',
  'Packed orders waiting for a driver': 'Đơn đã đóng gói đang chờ tài xế',
  Returns: 'Hàng trả lại',
  'Returned and rejected goods': 'Hàng được trả lại hoặc từ chối',
  'Logistics & Delivery': 'Hậu cần và giao hàng',
  'Route Planning': 'Lập kế hoạch tuyến đường',
  'Plan delivery runs': 'Lập kế hoạch các chuyến giao hàng',
  'Driver Dispatch': 'Điều phối tài xế',
  'Assign drivers and vehicles': 'Phân công tài xế và phương tiện',
  'Proof of Delivery': 'Xác nhận giao hàng',
  'Signatures and photos from drop-offs': 'Chữ ký và ảnh khi giao hàng',
  'Purchasing & Suppliers': 'Mua hàng và nhà cung cấp',
  'Incoming stock from farms and manufacturers': 'Hàng nhập từ trang trại và nhà sản xuất',
  Customers: 'Khách hàng',
  'Wholesale (B2B) and retail (B2C) buyers': 'Khách mua sỉ (B2B) và bán lẻ (B2C)',
  'Reports & Analytics': 'Báo cáo và phân tích',
  'Financials, yield and waste reporting': 'Báo cáo tài chính, sản lượng và hao hụt',
  Soon: 'Sắp ra mắt',
  'Expand sidebar': 'Mở rộng thanh bên',
  'Collapse sidebar': 'Thu gọn thanh bên',
  Reset: 'Đặt lại',
  'Toggle navigation': 'Bật/tắt điều hướng',
  'HappyBoxx home': 'Trang chủ HappyBoxx',
  'Open search': 'Mở tìm kiếm',
  Search: 'Tìm kiếm',
  'Search SKUs, products, orders, customers…': 'Tìm SKU, sản phẩm, đơn hàng, khách hàng…',
  'Search SKUs, products, pages…': 'Tìm SKU, sản phẩm, trang…',
  Products: 'Sản phẩm',
  'Go to': 'Đi đến',
  'Searching…': 'Đang tìm…',
  'No results. Order, batch and customer search arrives with those modules.':
    'Không có kết quả. Tìm kiếm đơn hàng, lô hàng và khách hàng sẽ có khi các phân hệ này được triển khai.',
  'Quick actions': 'Thao tác nhanh',
  New: 'Mới',
  'Create new': 'Tạo mới',
  'Catalog & stock': 'Danh mục và tồn kho',
  'New product': 'Sản phẩm mới',
  'New category': 'Danh mục mới',
  'Adjust stock': 'Điều chỉnh tồn kho',
  Operations: 'Vận hành',
  'Create order': 'Tạo đơn hàng',
  'Log delivery': 'Ghi nhận giao hàng',
  'Receive shipment': 'Nhận lô hàng',
  Notifications: 'Thông báo',
  alerts: 'cảnh báo',
  Alerts: 'Cảnh báo',
  'View all': 'Xem tất cả',
  "You're all caught up.": 'Bạn đã xem hết thông báo.',
  'Out of stock': 'Hết hàng',
  'Low stock': 'Tồn kho thấp',
  'on hand · reorder at': 'hiện có · mức đặt lại',
  'Expiry and delivery alerts will appear here once batch tracking and logistics go live.':
    'Cảnh báo hạn sử dụng và giao hàng sẽ xuất hiện tại đây khi tính năng quản lý lô hàng và hậu cần được triển khai.',
  'Light mode': 'Chế độ sáng',
  'Dark mode': 'Chế độ tối',
  'Language: English': 'Ngôn ngữ: Tiếng Việt',
  Warehouse: 'Kho hàng',
  'Switch warehouse': 'Chuyển kho',
  'Clock in / out': 'Chấm công vào / ra',
  'Account settings': 'Cài đặt tài khoản',
  'Sign out': 'Đăng xuất',
  "Today's overview of the warehouse.": 'Tổng quan kho hàng hôm nay.',
  'Active categories': 'Danh mục đang hoạt động',
  'Tracked stock': 'Tồn kho đang theo dõi',
  'Stock alerts': 'Cảnh báo tồn kho',
  'Items in the catalog': 'Sản phẩm trong danh mục',
  'Vegetables, fruits, containers…': 'Rau củ, trái cây, hộp đựng…',
  'Products with stock levels': 'Sản phẩm có theo dõi tồn kho',
  'Low or out of stock': 'Tồn kho thấp hoặc hết hàng',
  'Needs restocking': 'Cần bổ sung hàng',
  'On hand': 'Hiện có',
  Status: 'Trạng thái',
  'All tracked items are above their reorder level.':
    'Tất cả mặt hàng đang theo dõi đều cao hơn mức đặt hàng lại.',
  'Order pipeline': 'Quy trình đơn hàng',
  'Coming soon': 'Sắp ra mắt',
  Picking: 'Đang lấy hàng',
  Packed: 'Đã đóng gói',
  'Out for delivery': 'Đang giao hàng',
  'Live order counts and a Kanban board arrive with the Orders module.':
    'Số lượng đơn hàng trực tiếp và bảng Kanban sẽ có khi phân hệ Đơn hàng được triển khai.',
  Loading: 'Đang tải',
  "Couldn't load data": 'Không thể tải dữ liệu',
  Retry: 'Thử lại',
  'Nothing here yet': 'Chưa có dữ liệu',
  Active: 'Đang hoạt động',
  Inactive: 'Không hoạt động',
  Showing: 'Đang hiển thị',
  of: 'trên',
  'Rows per page': 'Số hàng mỗi trang',
  'Display unit': 'Đơn vị hiển thị',
  Pieces: 'Cái',
  Kilograms: 'Kilôgam',
  Grams: 'Gam',
  Bunches: 'Bó',
  Packs: 'Gói',
  Boxes: 'Hộp',
  Cartons: 'Thùng',
  'Close panel': 'Đóng bảng',
  Name: 'Tên',
  Description: 'Mô tả',
  'Last updated': 'Cập nhật lần cuối',
  'Create category': 'Tạo danh mục',
  'Save changes': 'Lưu thay đổi',
  Cancel: 'Hủy',
  Category: 'Danh mục',
  "Couldn't load category": 'Không thể tải danh mục',
  'e.g. Leafy greens': 'vd: Rau ăn lá',
  'Inactive categories are hidden from buyers': 'Danh mục không hoạt động sẽ bị ẩn với người mua',
  'Group products so staff and buyers can find them quickly.':
    'Nhóm sản phẩm để nhân viên và người mua dễ dàng tìm thấy.',
  'Search categories': 'Tìm danh mục',
  All: 'Tất cả',
  'No categories match your filters': 'Không có danh mục phù hợp với bộ lọc',
  'No categories yet': 'Chưa có danh mục',
  SKU: 'SKU',
  Product: 'Sản phẩm',
  Unit: 'Đơn vị',
  Price: 'Giá',
  'Manage the catalog: pricing, units and availability.':
    'Quản lý danh mục: giá, đơn vị và tình trạng cung ứng.',
  'Exports the rows currently shown': 'Xuất các hàng đang hiển thị',
  Export: 'Xuất',
  'Search products': 'Tìm sản phẩm',
  'Search name or SKU': 'Tìm theo tên hoặc SKU',
  'All categories': 'Tất cả danh mục',
  'No products match your filters': 'Không có sản phẩm phù hợp với bộ lọc',
  'No products yet': 'Chưa có sản phẩm',
  'Try a different search or reset the filters.': 'Thử tìm kiếm khác hoặc đặt lại bộ lọc.',
  'Add your first vegetable, fruit or container to start selling.':
    'Thêm rau củ, trái cây hoặc hộp đựng đầu tiên để bắt đầu bán hàng.',
  'Name is required': 'Vui lòng nhập tên',
  'was updated': 'đã được cập nhật',
  'was created': 'đã được tạo',
  'Category created': 'Đã tạo danh mục',
  'e.g. TOM-001': 'vd: TOM-001',
  'SKU cannot be changed': 'Không thể thay đổi SKU',
  'Select category': 'Chọn danh mục',
  'Product name': 'Tên sản phẩm',
  'e.g. Roma tomatoes': 'vd: Cà chua Roma',
  'Variety, grade, packaging notes…': 'Giống, phân loại, ghi chú đóng gói…',
  'Unit of measure': 'Đơn vị đo',
  'Price per': 'Giá mỗi',
  'Inactive products are hidden from buyers': 'Sản phẩm không hoạt động sẽ bị ẩn với người mua',
  'Add an item to the catalog': 'Thêm mặt hàng vào danh mục',
  'Create product': 'Tạo sản phẩm',
  "Couldn't load product": 'Không thể tải sản phẩm',
  Details: 'Chi tiết',
  'Batches, supplier & price history': 'Lô hàng, nhà cung cấp và lịch sử giá',
  'Batch numbers, supplier details, storage requirements and price history will appear here once the Purchasing module is live.':
    'Số lô, thông tin nhà cung cấp, yêu cầu bảo quản và lịch sử giá sẽ xuất hiện tại đây khi phân hệ Mua hàng được triển khai.',
  'Product details': 'Thông tin sản phẩm',
  'was added to the catalog': 'đã được thêm vào danh mục',
  'Product created': 'Đã tạo sản phẩm',
  'SKU is required': 'Vui lòng nhập SKU',
  'Letters, digits and dashes only': 'Chỉ chấp nhận chữ cái, chữ số và dấu gạch ngang',
  'Choose a category': 'Chọn danh mục',
  'Enter a price of 0 or more': 'Nhập giá từ 0 trở lên',
  Stock: 'Tồn kho',
  'In stock': 'Còn hàng',
  'Not tracked in inventory yet': 'Chưa theo dõi tồn kho',
  'Start tracking to record on-hand quantity and get low-stock alerts.':
    'Bắt đầu theo dõi để ghi nhận số lượng hiện có và nhận cảnh báo tồn kho thấp.',
  'Opening quantity': 'Số lượng ban đầu',
  'Start tracking': 'Bắt đầu theo dõi',
  'Stock tracking started': 'Đã bắt đầu theo dõi tồn kho',
  'is now tracked in inventory': 'hiện được theo dõi trong kho',
  Updated: 'Đã cập nhật',
  'on hand': 'hiện có',
  Only: 'Chỉ còn',
  'Adjust stock →': 'Điều chỉnh tồn kho →',
  "Couldn't load stock": 'Không thể tải tồn kho',
  'Not tracked': 'Chưa theo dõi',
  "This product isn't tracked in inventory yet.": 'Sản phẩm này chưa được theo dõi trong kho.',
  'View product details →': 'Xem chi tiết sản phẩm →',
  'Enter a quantity greater than 0': 'Nhập số lượng lớn hơn 0',
  'Stock updated': 'Đã cập nhật tồn kho',
  Quantity: 'Số lượng',
  'Receive (+)': 'Nhận hàng (+)',
  'Remove (−)': 'Xuất hàng (−)',
  'Receive stock': 'Nhận hàng vào kho',
  'Remove stock': 'Xuất hàng khỏi kho',
  'Reorder level': 'Mức đặt hàng lại',
  'Updated (UTC)': 'Cập nhật (UTC)',
  'On-hand quantities across the warehouse. Click a row to receive or remove stock.':
    'Số lượng hiện có trong kho. Chọn một hàng để nhận hoặc xuất hàng.',
  'Search SKU': 'Tìm SKU',
  'Stock filter': 'Lọc tồn kho',
  'All items': 'Tất cả mặt hàng',
  'Low / out of stock': 'Tồn kho thấp / hết hàng',
  'No stock items match your filters': 'Không có mặt hàng tồn kho phù hợp với bộ lọc',
  'No tracked stock yet': 'Chưa có tồn kho được theo dõi',
  'Open a product and choose "Start tracking" to record its stock level.':
    'Mở sản phẩm và chọn "Bắt đầu theo dõi" để ghi nhận mức tồn kho.',
  Planned: 'Đã lên kế hoạch',
  ' is on the roadmap': ' nằm trong lộ trình phát triển',
  "This module isn't available yet. The navigation is in place so you can see where it will live.":
    'Phân hệ này chưa khả dụng. Mục điều hướng đã có để bạn biết vị trí của tính năng trong tương lai.',
  'Back to dashboard': 'Quay lại bảng điều khiển',
  'Page not found': 'Không tìm thấy trang',
  "The page you're looking for doesn't exist or has moved.":
    'Trang bạn đang tìm không tồn tại hoặc đã được di chuyển.',
};

function getInitialLanguage(): UiLanguage {
  return localStorage.getItem(LANGUAGE_STORAGE_KEY) === 'vi' ? 'vi' : 'en';
}

export function UiLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<UiLanguage>(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = {
    language,
    setLanguage,
    t: (englishText: string) =>
      language === 'vi' ? (translations[englishText] ?? englishText) : englishText,
  };

  return <UiLanguageContext.Provider value={value}>{children}</UiLanguageContext.Provider>;
}
